package gregtech.loaders.preload;

import gregtech.api.util.GT_Log;
import gregtech.loaders.oreprocessing.*;

public class GT_Loader_OreProcessing
        implements Runnable {
    @Override
    public void run() {
        GT_Log.out.println("GT_Mod: Registering Autogenerated Recipe Processes.");
        new ProcessingAll();
        new ProcessingArrows();
        new ProcessingBeans();
        new ProcessingBlock();
        new ProcessingBolt();
        new ProcessingCell();
        new ProcessingCrate();
        new ProcessingCompressed();
        new ProcessingCrafting();
        new ProcessingCrop();
        new ProcessingCrushedOre();
        new ProcessingCrystallized();
        new ProcessingDirty();
        new ProcessingDust();
        new ProcessingDye();
        new ProcessingLens();
        new ProcessingShaping();
        new ProcessingGem();
        new ProcessingGear();
        new ProcessingIngot();
        new ProcessingItem();
        new ProcessingLog();
        new ProcessingTransforming();
        new ProcessingOre();
        new ProcessingOreSmelting();
        new ProcessingPlank();
        new ProcessingPlate();
        new ProcessingPure();
        new ProcessingRecycling();
        new ProcessingRotor();
        new ProcessingSand();
        new ProcessingSaplings();
        new ProcessingSlab();
        new ProcessingStick();
        new ProcessingStoneVarious();
        new ProcessingWax();
        //Now featuring 50% Less Components!
    }
}
